/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/957Dz5x2aDp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { Manrope } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

manrope({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client'

import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { useState, useEffect } from 'react'
import useSWR from 'swr'
 
const fetcher = (...args) => fetch(...args).then((res) => res.json())

export function Captions() {

  const url = 'http://localhost:8000/captions?location=paris&mood=happy&words=wonderful'

  var { data, mutate, error } = useSWR(url, fetcher)
  console.debug(error)
  console.log(error)
  if (error) data = "Just feel special."

  // // "Just had the most amazing time in Paris! The city of love really knows how to make a anyone feel special."
  // const [message, setMessage] = useState(null)
  // console.debug("URL: ", url);   // For logging URL and parameters, remove this line after testing is done to prevent leaking sensitive data like API keys in the browser's devtools network tab (remove or comment out if not needed).

  // const handleClick = () => {
  //   console.debug("Button clicked"); // For logging button click in browser devtools network tab for debugging purposes only (remove or comment out if not needed).
  //   fetch(url)
  //     .then((res) => res.json())
  //     .then(message => setMessage(message))
  //     .catch(error => console.error('Error fetching data:', error));
  // };

  // call api endpoint http://localhost:8000/captions and get response


  return (
    <div className="px-4 py-6 md:px-6 md:py-12">
      <div className="flex flex-col gap-4">
        <div className="rounded-lg border border-gray-200 dark:border-gray-800 dark:border-gray-800">
          <div className="grid grid-cols-1 md:grid-cols-3 divide-y md:divide-y-0 divide-gray-200 dark:divide-gray-800">
            <div className="flex flex-1 items-center min-h-[200px] p-4 md:p-6">
              <div className="space-y-2">
                <h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Generate Instagram Captions</h1>
                <p className="text-gray-500 dark:text-gray-400">Get the perfect caption for your post</p>
              </div>
            </div>
            <div className="flex flex-1 items-center min-h-[200px] p-4 md:p-6">
              <form className="flex-1 grid gap-4">
                <div className="space-y-2">
                  <Label htmlFor="location">Location</Label>
                  <Input id="location" placeholder="E.g. Paris" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="feeling">Feeling</Label>
                  <Input id="feeling" placeholder="E.g. happy" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="words">Words to include</Label>
                  <Input id="words" placeholder="E.g. beach, sunset" />
                </div>
                <Button size="lg" onClick={() => mutate()}>Generate</Button>
              </form>
            </div>
          </div>
        </div>
        <div className="rounded-lg border border-gray-200 dark:border-gray-800 dark:border-gray-800">
          <div className="p-4 md:p-6">
            <div className="grid gap-4">
              <div className="text-sm font-semibold tracking-wide uppercase text-gray-500 dark:text-gray-400">
                Your perfect caption
              </div>
              <div className="prose prose-gray max-w-none">
                <p>
                  {data} 😍🇫🇷
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
